# Generated by Django 5.1.1 on 2024-09-30 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.get_current_timezone),
        ),
    ]
