# Generated by Django 5.1.1 on 2024-09-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_gamepost_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
