# Generated by Django 5.1.1 on 2024-09-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_gamepost_author_alter_gamepost_publish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamepost',
            options={'ordering': ['-time_create', 'title', 'publish'], 'verbose_name': 'Блог о играх', 'verbose_name_plural': 'Блог о играх'},
        ),
        migrations.RemoveField(
            model_name='gamepost',
            name='author',
        ),
    ]
