# Generated by Django 5.1.1 on 2024-09-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_gamepost_options_gamepost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamepost',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Блог о играх', 'verbose_name_plural': 'Блог о играх'},
        ),
    ]
