# Generated by Django 5.1.1 on 2024-09-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_gamepost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamepost',
            options={'ordering': ['-publish'], 'verbose_name': 'Блог о играх', 'verbose_name_plural': 'Блог о играх'},
        ),
    ]
