# Generated by Django 5.1.1 on 2024-09-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_gamepost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamepost',
            options={},
        ),
    ]
