# Generated by Django 5.1.2 on 2024-10-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
