# Generated by Django 5.1.2 on 2024-10-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgre', '0002_part_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
