# Generated by Django 5.1.1 on 2024-09-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userextension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextension',
            options={},
        ),
        migrations.AlterField(
            model_name='userextension',
            name='paginate',
            field=models.IntegerField(default=3),
        ),
    ]
